openapi: 3.0.0
info:
  title: Sanction List API
  version: '1.0'
  description: "cubemos Sanction list API is a RESTful API which can be used to avoid prosecution and be compliant with international regulation on sanction, AML and financial crime. \n\n### Description\n[Introduction](../docs/01Welcome.md)  [Quickstart](../docs/04Quickstart.md)"
  contact:
    name: cubemos gmbh
    url: www.cubemos.com
    email: meet@cubemos.com
  license:
    name: cubemos license
  termsOfService: 'https://www.cubemos.com/general-terms/'
servers:
  - url: 'https://api.cubemos.com/sanction'
paths:
  /search/entities/person:
    post:
      summary: person search
      operationId: post-search-entities-person
      responses:
        '200':
          description: 'The request was created successfully and the results are available as an array. If the array is empty, there were no matching persons found in the desired sanction lists.'
          headers: {}
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/person'
                type: array
              examples:
                example:
                  value:
                    persons:
                      - person:
                          first_name: Serhii
                          middle_name: ''
                          last_name: Kliuiev
                          dob: 19.08.1969
                          gender: male
                          alias:
                            - Serhiy Klyuyev
                          nationalities:
                            - UA
                          list_entry_url: 'https://sanction-api.cubemos.com/list/cfsp?id=12345'
                      - person:
                          first_name: Serhii
                          middle_name: ''
                          last_name: Kliuiev
                          dob: 19.08.1969
                          gender: male
                          alias:
                            - Serhiy Klyuyev
                          nationalities:
                            - UA
                          list_entry_url: 'https://sanction-api.cubemos.com/list/cfsp?id=12345'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      description: "### Search a person through sanction lists\nThis API call allows you to perform a search through the desired sanction lists for a person. The search results returned are a list of all entries from the sanction lists which match to the input along with the degree of the match. "
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/personSearch'
            examples:
              Example:
                value:
                  person_search:
                    search_config:
                      sanction_lists:
                        - cfsp
                        - sdn
                      must_match_attributes:
                        - last_name
                        - nationality
                    person:
                      first_name: Serhii
                      middle_name: ''
                      last_name: Kliuiev
                      full_name: Serhii Kliuiev
                      alias: Serhiy Klyuyev
                      gender: male
                      nationality: UA
                      dob: 19.08.1969
          application/xml:
            schema:
              type: object
              properties: {}
          multipart/form-data:
            schema:
              type: object
              properties: {}
          text/html:
            schema:
              type: object
              properties: {}
          text/plain:
            schema:
              type: object
              properties: {}
          application/EDI-X12:
            schema:
              type: object
              properties: {}
        description: "### Payload request schema for single search\nIn order to perform a search on a person through the sanction lists, the full name and the desired sanction lists are required. Please note that the higher the ambiguity in input, the bigger could be the output response payload.  "
      parameters: []
      tags:
        - Entity Search
      security:
        - API Key: []
    parameters: []
  /search/entities/organization:
    post:
      summary: organization search
      operationId: post-search-entities-organization
      responses:
        '200':
          description: 'The request was created successfully and the results are available as an array. If the array is empty, there were no matching organization found in the desired sanction lists.'
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/organization'
                type: array
              examples:
                example:
                  value:
                    organizations:
                      - organization:
                          address:
                            country: DE
                            zip_code: 12345
                            city: Berlin
                            street: Hermann Straße 1
                          headquarter_country: DE
                          aliases: []
                          list_entry_url: 'https://sanction-api.cubemos.com/list/cfsp?id=12345'
                      - organization:
                          address:
                            country: DE
                            zip_code: 87654
                            city: Munich
                            street: Hermann Straße 1
                          headquarter_country: DE
                          aliases: []
                          list_entry_url: 'https://sanction-api.cubemos.com/list/cfsp?id=12345'
          headers: {}
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/organizationSearch'
            examples:
              Example:
                value:
                  organization_search:
                    search_config:
                      sanction_lists:
                        - cfsp
                        - sdn
                    organization:
                      name: cubemos gmbh
                      country_code: DE
        description: "### Payload request schema for single search\nIn order to perform a search on an organization through the sanction lists, the name and the desired sanction lists are required. Please note that the higher the ambiguity in input, the bigger could be the output response payload.  "
      description: "### Search an organization through sanction lists\nThis API call allows you to perform a search through the desired sanction lists for an organization. The search results returned are a list of all entries from the sanction lists which match to the input along with the degree of the match. "
      tags:
        - Entity Search
      security:
        - API Key: []
    parameters: []
  /search/location/address:
    post:
      summary: address search
      operationId: post-search-address
      responses:
        '200':
          description: 'The request was created successfully and the results are available as an array. If the array is empty, there were no matching persons found in the desired sanction lists.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/locationSearchResult'
              examples:
                example:
                  value:
                    persons:
                      - person:
                          first_name: Serhii
                          middle_name: ''
                          last_name: Kliuiev
                          dob: 19.08.1969
                          gender: male
                          alias:
                            - Serhiy Klyuyev
                          nationalities:
                            - UA
                          list_entry_url: 'https://sanction-api.cubemos.com/list/cfsp?id=12345'
                      - person:
                          first_name: Serhii
                          middle_name: ''
                          last_name: Kliuiev
                          dob: 19.08.1969
                          gender: male
                          alias:
                            - Serhiy Klyuyev
                          nationalities:
                            - UA
                          list_entry_url: 'https://sanction-api.cubemos.com/list/cfsp?id=12345'
                    organizations:
                      - organization:
                          address:
                            country: DE
                            zip_code: 12345
                            city: Berlin
                            street: Hermann Straße 1
                          headquarter_country: DE
                          aliases: []
                          list_entry_url: 'https://sanction-api.cubemos.com/list/cfsp?id=12345'
                      - organization:
                          address:
                            country: DE
                            zip_code: 87654
                            city: Munich
                            street: Hermann Straße 1
                          headquarter_country: DE
                          aliases: []
                          list_entry_url: 'https://sanction-api.cubemos.com/list/cfsp?id=12345'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addressSearch'
            examples:
              Example:
                value:
                  sanction_lists:
                    - EU-financial sanction list
                    - UN-sanction list
                  address:
                    country: DE
                    zip_code: 12345
                    city: Berlin
                    street: Hermann Straße 1
        description: "### Payload request scheme for single search\nIn order to search for a location bassed on the address, the sanction lists as well as the address details are required. Please note that the higher the ambiguity in input, the bigger could be the output response payload.  "
      description: "### Search on an entity through the desired sanction lists in at an address\nThis API call allows you to perform a search through the desired sanction lists for all the sanctioned entities at the desired location. "
      tags:
        - Entity Search
      security:
        - API Key: []
    parameters: []
  '/list/cfsp/{id}':
    get:
      summary: CFSP list entry
      tags:
        - Sanction List Entry
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cfsp'
              examples:
                example:
                  value:
                    fileGenerationDate: 29/04/2020
                    Entity_LogicalId: 43
                    Entity_EU_ReferenceNumber: EU.85.7
                    Entity_UnitedNationId: ''
                    Entity_DesignationDate: ''
                    Entity_DesignationDetails: ''
                    Entity_Remark: (UNSC RESOLUTION 1483 BASIS)
                    Entity_SubjectType: P
                    Entity_SubjectType_ClassificationCode: person
                    Entity_Regulation_Type: regulation
                    Entity_Regulation_OrganisationType: commission
                    Entity_Regulation_PublicationDate: '2003-07-08'
                    Entity_Regulation_EntryIntoForceDate: '2003-07-07'
                    Entity_Regulation_NumberTitle: 1210/2003 (OJ L169)
                    Entity_Regulation_Programme: IRQ
                    Entity_Regulation_PublicationUrl: 'http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2003:169:0006:0023:EN:PDF'
                    NameAlias_LastName: ''
                    NameAlias_FirstName: ''
                    NameAlias_MiddleName: ''
                    NameAlias_WholeName: Aziz Salih al-Numan
                    NameAlias_NameLanguage: ''
                    NameAlias_Gender: ''
                    NameAlias_Title: ''
                    NameAlias_Function: Former Governor of Karbala and An Najaf;
                    NameAlias_LogicalId: 64
                    NameAlias_RegulationLanguage: EN
                    NameAlias_Remark: ''
                    NameAlias_Regulation_Type: regulation
                    NameAlias_Regulation_OrganisationType: commission
                    NameAlias_Regulation_PublicationDate: '2003-07-08'
                    NameAlias_Regulation_EntryIntoForceDate: '2003-07-07'
                    NameAlias_Regulation_NumberTitle: 1210/2003 (OJ L169)
                    NameAlias_Regulation_Programme: IRQ
                    NameAlias_Regulation_PublicationUrl: 'http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2003:169:0006:0023:EN:PDF'
                    Address_City: ''
                    Address_Street: ''
                    Address_PoBox: ''
                    Address_ZipCode: ''
                    Address_Region: ''
                    Address_Place: ''
                    Address_AsAtListingTime: ''
                    Address_ContactInfo: ''
                    Address_CountryIso2Code: ''
                    Address_CountryDescription: ''
                    Address_LogicalId: ''
                    Address_RegulationLanguage: ''
                    Address_Remark: ''
                    Address_Regulation_Type: ''
                    Address_Regulation_OrganisationType: ''
                    Address_Regulation_PublicationDate: ''
                    Address_Regulation_EntryIntoForceDate: ''
                    Address_Regulation_NumberTitle: ''
                    Address_Regulation_Programme: ''
                    Address_Regulation_PublicationUrl: ''
                    BirthDate_BirthDate: ''
                    BirthDate_Day: ''
                    BirthDate_Month: ''
                    BirthDate_Year: ''
                    BirthDate_YearRangeFrom: ''
                    BirthDate_YearRangeTo: ''
                    BirthDate_Circa: ''
                    BirthDate_CalendarType: ''
                    BirthDate_ZipCode: ''
                    BirthDate_Region: ''
                    BirthDate_Place: ''
                    BirthDate_City: ''
                    BirthDate_CountryIso2Code: ''
                    BirthDate_CountryDescription: ''
                    BirthDate_LogicalId: ''
                    BirthDate_RegulationLanguage: ''
                    BirthDate_Remark: ''
                    BirthDate_Regulation_Type: ''
                    BirthDate_Regulation_OrganisationType: ''
                    BirthDate_Regulation_PublicationDate: ''
                    BirthDate_Regulation_EntryIntoForceDate: ''
                    BirthDate_Regulation_NumberTitle: ''
                    BirthDate_Regulation_Programme: ''
                    BirthDate_Regulation_PublicationUrl: ''
                    Identification_Number: ''
                    Identification_Diplomatic: ''
                    Identification_KnownExpired: ''
                    Identification_KnownFalse: ''
                    Identification_ReportedLost: ''
                    Identification_RevokedByIssuer: ''
                    Identification_IssuedBy: ''
                    Identification_IssuedDate: ''
                    Identification_ValidFrom: ''
                    Identification_ValidTo: ''
                    Identification_LatinNumber: ''
                    Identification_NameOnDocument: ''
                    Identification_TypeCode: ''
                    Identification_TypeDescription: ''
                    Identification_Region: ''
                    Identification_CountryIso2Code: ''
                    Identification_CountryDescription: ''
                    Identification_LogicalId: ''
                    Identification_RegulationLanguage: ''
                    Identification_Remark: ''
                    Identification_Regulation_Type: ''
                    Identification_Regulation_OrganisationType: ''
                    Identification_Regulation_PublicationDate: ''
                    Identification_Regulation_EntryIntoForceDate: ''
                    Identification_Regulation_NumberTitle: ''
                    Identification_Regulation_Programme: ''
                    Identification_Regulation_PublicationUrl: ''
                    Citizenship_Region: ''
                    Citizenship_CountryIso2Code: ''
                    Citizenship_CountryDescription: ''
                    Citizenship_LogicalId: ''
                    Citizenship_RegulationLanguage: ''
                    Citizenship_Remark: ''
                    Citizenship_Regulation_Type: ''
                    Citizenship_Regulation_OrganisationType: ''
                    Citizenship_Regulation_PublicationDate: ''
                    Citizenship_Regulation_EntryIntoForceDate: ''
                    Citizenship_Regulation_NumberTitle: ''
                    Citizenship_Regulation_Programme: ''
                    Citizenship_Regulation_PublicationUrl: ''
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      operationId: get-search-sanction-list-entry
      description: 'Get the entry from the official [CFSP sanction list](https://eeas.europa.eu/headquarters/headquarters-homepage_en/8442/Consolidated%20list%20of%20sanction) based on the result from the search calls. '
      parameters: []
      security:
        - API Key: []
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: The entity logical ID in the CFSP sanction list from which all the entries will be returned
  '/list/sdn/{id}':
    get:
      summary: SDN list entry
      tags:
        - Sanction List Entry
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sdn'
              examples:
                example:
                  value:
                    entity_number: '10133'
                    sdn:
                      - sdn_name: SNIPER AFRICA
                        sdn_type: '-0- '
                        program: SDGT
                        title: '-0- '
                        call_sign: '-0- '
                        vess_type: '-0- '
                        tonnage: '-0- '
                        grt: '-0- '
                        vess_flag: '-0- '
                        vess_owner: '-0- '
                        remarks: Website www.sniperafrica.com; Registration ID 200302847123; Tax ID No. 9113562152.
                    alt:
                      - alt_num: '9835'
                        alt_type: aka
                        alt_name: SNIPER OUTDOOR CC
                        alt_remarks: '-0-'
                      - alt_num: '9836'
                        alt_type: aka
                        alt_name: SNIPER OUTDOORS CC
                        alt_remarks: '-0-'
                      - alt_num: '9837'
                        alt_type: aka
                        alt_name: TRUE MOTIVES 1236 CC
                        alt_remarks: '-0-'
                    add:
                      - add_num: '13533'
                        address: '40 Mint Road, Amoka Gardens, Fordsburg'
                        city_province_postalcode: Johannesburg
                        country: South Africa
                        add_remarks: '-0-'
                      - add_num: '13534'
                        address: P.O. Box 42928
                        city_province_postalcode: Fordsburg 2003
                        country: South Africa
                        add_remarks: '-0-'
                      - add_num: '13535'
                        address: 16 Gold Street
                        city_province_postalcode: Carletonville 2500
                        country: South Africa
                        add_remarks: '-0-'
                      - add_num: '13536'
                        address: P.O. Box 28215
                        city_province_postalcode: Kensington 2101
                        country: South Africa
                        add_remarks: '-0-'
                    sdn_comments: []
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      operationId: get-list-sdn
      description: 'Get the entry from the official [SDN sanction lists](https://www.treasury.gov/resource-center/sanction/sdn-list/pages/default.aspx) based on the result from the search calls'
      security:
        - API Key: []
    parameters:
      - schema:
          type: string
        name: id
        in: path
        description: The UID in the SDN sanction list from which all the entries will be returned
        required: true
components:
  schemas:
    personSearchAttributes:
      title: personSearchAttributes
      type: object
      description: Search identifiers for a person through the sanction list
      x-examples: {}
      properties:
        full_name:
          type: string
          description: Full name of a person (first_names + middle_names + last_names )
          example: john junior senior smith
        first_name:
          type: string
          description: All the known first names of the person
          example: john
        middle_name:
          type: string
          description: All the known middle names of the person
          example: junior senior
        last_name:
          type: string
          description: All the known last names of the person
          example: smith
        alias:
          description: Alias of the person
          example: 'don john, godfather'
          type: string
        gender:
          type: string
          description: 'Gender of the person '
          example: male
        dob:
          type: string
          description: The date of birth of the person known
          example: 01.01.1950
        city:
          type: string
          description: The city in which the person was known to reside
          example: Berlin
        nationality:
          type: string
          example: DE
          description: The 2 letter ISO code of the nationality of the person known
      required:
        - full_name
    searchConfig:
      title: search config
      type: object
      description: configure the search on the desired entity
      properties:
        sanction_lists:
          type: array
          description: All the sanction list names through which the search has to be made
          items:
            type: string
        must_match_attributes:
          type: array
          description: 'Identifiers of the entry fields against which the output field has to be a 100% match'
          items:
            type: string
      required:
        - sanction_lists
    personSearch:
      title: personSearch
      type: object
      description: The identifiers based on which the search will be performed for a person through the desired sanction lists
      x-examples: {}
      properties:
        search_config:
          $ref: '#/components/schemas/searchConfig'
        person:
          $ref: '#/components/schemas/personSearchAttributes'
    organizationSearchAttributes:
      title: organizationSearchAttributes
      type: object
      description: Search for an organization through a sanction list
      properties:
        name:
          type: string
          description: Name of the organization
          example: cubemos gmbh
        country_code:
          type: string
          description: 2 digit ISO country code of the place where the organization is located
          example: DE
    organizationSearch:
      title: organizationSearch
      type: object
      description: The identifiers based on which the search will be performed for a organization through the desired sanction lists
      properties:
        search_config:
          $ref: '#/components/schemas/searchConfig'
        organization:
          $ref: '#/components/schemas/organizationSearchAttributes'
    organization:
      title: organization
      type: object
      description: organization details
      properties:
        name:
          type: string
          description: Name of the organization
        address:
          $ref: '#/components/schemas/address'
        aliases:
          type: array
          description: "List of all the aliases that the organization has for it's name"
          items:
            type: string
        list_entry_url:
          type: string
          description: The URL to the list entry which can be used with the GET call to obtain the raw entries from the sanction list in which the result is extracted from
      required:
        - name
        - address
        - aliases
        - list_entry_url
    locationSearchResult:
      title: locationSearchResult
      type: object
      description: Response of a search query based on address through the desired sanction lists
      properties:
        persons:
          type: array
          items:
            $ref: '#/components/schemas/person'
        organizations:
          type: array
          items:
            $ref: '#/components/schemas/organization'
      required:
        - persons
        - organizations
    addressSearch:
      title: addressSearch
      type: object
      description: query payload for an address search
      x-examples: {}
      properties:
        search_config:
          $ref: '#/components/schemas/searchConfig'
        address:
          $ref: '#/components/schemas/address'
      required:
        - search_config
        - address
    person:
      title: person
      type: object
      description: person details
      x-examples: {}
      properties:
        full_name:
          type: string
          description: Full name of the sanctioned person
        first_name:
          type: string
          description: First name of the queried person
        middle_name:
          type: string
          description: Middle name of the queried person
        last_name:
          type: string
          description: Last name of the queried person
        dob:
          type: string
          description: Date of birth of the queried person
        gender:
          type: string
          description: Gender of the queried person
        aliases:
          type: array
          description: List of all the aliases that the queried person has
          items:
            type: string
        city:
          type: string
          description: City where the person is known to be located
        nationality:
          description: Nationality of the person
          type: string
        list_entry_url:
          type: string
          description: The URL to the list entry which can be used with the GET call to obtain the raw entries from the sanction list in which the result is extracted from
      required:
        - full_name
        - dob
        - gender
        - aliases
        - city
        - nationality
        - list_entry_url
    address:
      title: address
      type: object
      description: Basic search identifiers for the address to search through a sanction list where a sanctioned entity might be present
      properties:
        country_code:
          type: string
          description: '2 digit ISO country code '
        zip_code:
          type: string
          description: 'Zip code of the area '
        city:
          type: string
          description: Name of the city
        street:
          type: string
          description: Name of the street
    sdn:
      title: sdn
      type: object
      x-examples: {}
      description: Output payload of the entry from the SDN lists
      properties:
        entity_number:
          type: string
        sdn:
          type: array
          items:
            type: object
            properties:
              sdn_name:
                type: string
              sdn_type:
                type: string
              program:
                type: string
              title:
                type: string
              call_sign:
                type: string
              vess_type:
                type: string
              tonnage:
                type: string
              grt:
                type: string
              vess_flag:
                type: string
              vess_owner:
                type: string
              remarks:
                type: string
        alt:
          type: array
          items:
            type: object
            properties:
              alt_num:
                type: string
              alt_type:
                type: string
              alt_name:
                type: string
              alt_remarks:
                type: string
        add:
          type: array
          items:
            type: object
            properties:
              add_num:
                type: string
              address:
                type: string
              city_province_postalcode:
                type: string
              country:
                type: string
              add_remarks:
                type: string
        sdn_comments:
          type: array
          items:
            type: string
    cfsp:
      title: cfsp
      type: object
      x-examples: {}
      properties:
        fileGenerationDate:
          type: string
        Entity_LogicalId:
          type: integer
        Entity_EU_ReferenceNumber:
          type: string
        Entity_UnitedNationId:
          type: string
        Entity_DesignationDate:
          type: string
        Entity_DesignationDetails:
          type: string
        Entity_Remark:
          type: string
        Entity_SubjectType:
          type: string
        Entity_SubjectType_ClassificationCode:
          type: string
        Entity_Regulation_Type:
          type: string
        Entity_Regulation_OrganisationType:
          type: string
        Entity_Regulation_PublicationDate:
          type: string
        Entity_Regulation_EntryIntoForceDate:
          type: string
        Entity_Regulation_NumberTitle:
          type: string
        Entity_Regulation_Programme:
          type: string
        Entity_Regulation_PublicationUrl:
          type: string
        NameAlias_FirstName:
          type: string
        NameAlias_MiddleName:
          type: string
        NameAlias_WholeName:
          type: string
        NameAlias_NameLanguage:
          type: string
        NameAlias_Gender:
          type: string
        NameAlias_Title:
          type: string
        NameAlias_Function:
          type: string
        NameAlias_LogicalId:
          type: string
        NameAlias_RegulationLanguage:
          type: string
        NameAlias_Remark:
          type: string
        NameAlias_Regulation_Type:
          type: string
        NameAlias_Regulation_OrganisationType:
          type: string
        NameAlias_Regulation_PublicationDate:
          type: string
        NameAlias_Regulation_EntryIntoForceDate:
          type: string
        NameAlias_Regulation_NumberTitle:
          type: string
        NameAlias_Regulation_Programme:
          type: string
        NameAlias_Regulation_PublicationUrl:
          type: string
        Address_City:
          type: string
        Address_Street:
          type: string
        Address_PoBox:
          type: string
        Address_ZipCode:
          type: string
        Address_Region:
          type: string
        Address_Place:
          type: string
        Address_AsAtListingTime:
          type: string
        Address_ContactInfo:
          type: string
        Address_CountryIso2Code:
          type: string
        Address_CountryDescription:
          type: string
        Address_LogicalId:
          type: string
        Address_RegulationLanguage:
          type: string
        Address_Remark:
          type: string
        Address_Regulation_Type:
          type: string
        Address_Regulation_OrganisationType:
          type: string
        Address_Regulation_PublicationDate:
          type: string
        Address_Regulation_EntryIntoForceDate:
          type: string
        Address_Regulation_NumberTitle:
          type: string
        Address_Regulation_Programme:
          type: string
        Address_Regulation_PublicationUrl:
          type: string
        BirthDate_BirthDate:
          type: string
        BirthDate_Day:
          type: string
        BirthDate_Month:
          type: string
        BirthDate_Year:
          type: string
        BirthDate_YearRangeFrom:
          type: string
        BirthDate_YearRangeTo:
          type: string
        BirthDate_Circa:
          type: string
        BirthDate_CalendarType:
          type: string
        BirthDate_ZipCode:
          type: string
        BirthDate_Region:
          type: string
        BirthDate_Place:
          type: string
        BirthDate_City:
          type: string
        BirthDate_CountryIso2Code:
          type: string
        BirthDate_CountryDescription:
          type: string
        BirthDate_LogicalId:
          type: string
        BirthDate_RegulationLanguage:
          type: string
        BirthDate_Remark:
          type: string
        BirthDate_Regulation_Type:
          type: string
        BirthDate_Regulation_OrganisationType:
          type: string
        BirthDate_Regulation_PublicationDate:
          type: string
        BirthDate_Regulation_EntryIntoForceDate:
          type: string
        BirthDate_Regulation_NumberTitle:
          type: string
        BirthDate_Regulation_Programme:
          type: string
        BirthDate_Regulation_PublicationUrl:
          type: string
        Identification_Number:
          type: string
        Identification_Diplomatic:
          type: string
        Identification_KnownExpired:
          type: string
        Identification_KnownFalse:
          type: string
        Identification_ReportedLost:
          type: string
        Identification_RevokedByIssuer:
          type: string
        Identification_IssuedBy:
          type: string
        Identification_IssuedDate:
          type: string
        Identification_ValidFrom:
          type: string
        Identification_ValidTo:
          type: string
        Identification_LatinNumber:
          type: string
        Identification_NameOnDocument:
          type: string
        Identification_TypeCode:
          type: string
        Identification_TypeDescription:
          type: string
        Identification_Region:
          type: string
        Identification_CountryIso2Code:
          type: string
        Identification_CountryDescription:
          type: string
        Identification_LogicalId:
          type: string
        Identification_RegulationLanguage:
          type: string
        Identification_Remark:
          type: string
        Identification_Regulation_Type:
          type: string
        Identification_Regulation_OrganisationType:
          type: string
        Identification_Regulation_PublicationDate:
          type: string
        Identification_Regulation_EntryIntoForceDate:
          type: string
        Identification_Regulation_NumberTitle:
          type: string
        Identification_Regulation_Programme:
          type: string
        Identification_Regulation_PublicationUrl:
          type: string
        Citizenship_Region:
          type: string
        Citizenship_CountryIso2Code:
          type: string
        Citizenship_CountryDescription:
          type: string
        Citizenship_LogicalId:
          type: string
        Citizenship_RegulationLanguage:
          type: string
        Citizenship_Remark:
          type: string
        Citizenship_Regulation_Type:
          type: string
        Citizenship_Regulation_OrganisationType:
          type: string
        Citizenship_Regulation_PublicationDate:
          type: string
        Citizenship_Regulation_EntryIntoForceDate:
          type: string
        Citizenship_Regulation_NumberTitle:
          type: string
        Citizenship_Regulation_Programme:
          type: string
        Citizenship_Regulation_PublicationUrl:
          type: string
        NameAlias_LastName:
          type: string
      description: Output payload of the entry from the CFSP sanction list
  securitySchemes:
    API Key:
      name: x-api-key
      type: apiKey
      in: header
tags:
  - name: Sanction List Entry
    description: Full reference information in an official sanction list
  - name: Entity Search
    description: Perform a search for a single entity
